apiVersion: v1
kind: Pod
metadata:
  name: ecom-db-pod
  labels:
    name: ecom-db-pod
    app: ecom-app
spec:
  containers:
    - name: ecom-db-pod
      image: lethang7794/ecom-db:v1
      ports:
        - containerPort: 3036
      env:
        - name: MARIADB_DATABASE
          value: "ecomdb"
        - name: MARIADB_ROOT_PASSWORD
          value: "password"