apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: postgres-service
    app: demo-app
spec:
  selector:
    name: postgres-pod
    app: demo-app
  # type: ClusterIP
  ports:
    - port: 5432
      # protocol: TCP
      targetPort: 5432
