apiVersion: v1
kind: Service
metadata:
  name: ecom-web-service
spec:
  selector:
    name: ecom-web-pod
    app: ecom-app
  ports:
    - protocol: TCP
      nodePort: 30001
      port: 80
      targetPort: 80
  type: LoadBalancer