apiVersion: v1
kind: Pod
metadata:
  name: ecom-db-pod
  labels:
    name: ecom-db-pod
    app: ecom-app
spec:
  containers:
    - name: ecom-db-pod
      image: lethang7794/ecom-db:v1
      ports:
        - containerPort: 3306
      env:
        - name: MARIADB_USER
          value: "db_user"
        - name: MARIADB_PASSWORD
          value: "password"
        - name: MARIADB_ROOT_PASSWORD
          value: "root_password"
        - name: MARIADB_DATABASE
          value: "ecomdb"
