apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv-storage
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  hostPath:
    path: "/mnt/data/my-volume"