apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{ include "common.labels.standard" . | nindent 4 }}
type: Opaque
data:
  mariadb-root-password: {{ required "A MariaDB Root Password is required!" .Values.mariadb.auth.rootPassword | b64enc | quote }}
  mariadb-password: {{ required "A MariaDB Database Password is required!" .Values.mariadb.auth.password | b64enc | quote }}
  username: {{ print .Values.mariadb.auth.username | b64enc | quote }}
  database: {{ print .Values.mariadb.auth.database | b64enc | quote }}
