apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: demo-app
spec:
  selector:
    name: redis-pod
    app: demo-app
  # type: ClusterIP
  ports:
    - port: 6379
      # protocol: TCP
      targetPort: 6379
